{
 "title": "Kubernetes Cluster Status (Prometheus)",
 "description": "Kubernetes Cluster Status (Prometheus)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Control Plane UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(up{job=~\"apiserver|kube-scheduler|kube-controller-manager\"} == 0)"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  { "title": "Control Plane Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "API Servers UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"apiserver\"} == 1) / count(up{job=\"apiserver\"})) * 100"
    }
   ]
  },
  {
   "title": "Controller Managers UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-controller-manager\"} == 1) / count(up{job=\"kube-controller-manager\"})) * 100"
    }
   ]
  },
  {
   "title": "Schedulers UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-scheduler\"} == 1) / count(up{job=\"kube-scheduler\"})) * 100"
    }
   ]
  },
  {
   "title": "Crashlooping Control Plane Pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total{namespace=~\"kube-system\"}[1h]) > 5)"
    }
   ]
  },
  { "title": "Capacity Planning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": ":node_cpu_utilisation:avg1m*100"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "expr": ":node_memory_utilisation:*100" }
   ]
  },
  {
   "title": "Filesystem Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(Sum(node:node_filesystem_usage:) / (sum(node:node_filesystem_avail:) + sum(node:node_filesystem_usage:)))*100"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  }
 ]
}